services:
  postgres:
    image: postgres:18.1
    container_name: voz-ativa-postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql
    networks:
      - voz-ativa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  voz-ativa-network:
    driver: bridge

volumes:
  voz-ativa-volume:
